### ISSUE TITLE
Fails on Ubuntu 14.04 with v0.10.25

### ISSUE THREAD

**Issue by pjump** [laverdet/node-fibers#216]
Running `node test.js`:

already-running.js: pass
bad-context.js: pass
child-process.js: *fail*
code: 0
stderr: 
stdout: 
/home/pskocik/dev/contrib/node-fibers/test/child-process.js:18
	var fn = Fiber(function() {
	         ^
TypeError: undefined is not a function
    at child (/home/pskocik/dev/contrib/node-fibers/test/child-process.js:18:11)
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/child-process.js:27:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

current.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/current.js:4
Fiber(function() {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/current.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
exec.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/exec.js:8
	Fiber(function() {
	^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/exec.js:8:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
exit.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/exit.js:10
		Fiber(function() {
		^
TypeError: undefined is not a function
    at null._onTimeout (/home/pskocik/dev/contrib/node-fibers/test/exit.js:10:3)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

stdout: pass

fibonacci.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/fibonacci.js:4
	return Fiber.prototype.run.bind(Fiber(function() {
	            ^
TypeError: Cannot read property 'prototype' of undefined
    at Fibonacci (/home/pskocik/dev/contrib/node-fibers/test/fibonacci.js:4:14)
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/fibonacci.js:16:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
finish-multiple.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/finish-multiple.js:3
Fiber(function() {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/finish-multiple.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
future-exception.js: *fail*
code: 7
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/future-exception.js:23
		throw err;
		      ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/future-exception.js:28:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
future.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/future.js:414
			Fiber(function() {
			^
TypeError: undefined is not a function
    at /home/pskocik/dev/contrib/node-fibers/future.js:414:4
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
illegal-yield.js: pass
pool.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/pool.js:6
		var fn = Fiber(function() {
		         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/pool.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
process-title.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/process-title.js:5
Fiber(function() {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/process-title.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
stack-overflow.js: *fail*
code: 0
stderr: 
stdout: 
stack-overflow2.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/stack-overflow2.js:2
Fiber(function() {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/stack-overflow2.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
started.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/started.js:3
Fiber(function() {
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/started.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout: 
unwind.js: *fail*
code: 8
stderr: 
/home/pskocik/dev/contrib/node-fibers/test/unwind.js:4
var fn = Fiber(function() {
         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pskocik/dev/contrib/node-fibers/test/unwind.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

stdout:

**Comment by laverdet** [comment]
68da69d8e2af85cb5d0cea6ff4fdd492e5700bba
