### ISSUE TITLE
Windows error with Meteor?

### ISSUE THREAD

**Issue by sonicviz** [laverdet/node-fibers#235]
Hi,
I'm getting this cryptic error with Future.js trying to run meteor from 3 different open source meteor repos.

error:
C:\Users\Paul\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
throw(ex);
^
SyntaxError: Unexpected token

I've posted three issues at the repos where the problem occurs but no solution so far:
https://github.com/Differential/meteor-boilerplate/issues/73
https://github.com/matteodem/meteor-boilerplate/issues/90
https://github.com/libreboard/libreboard/issues/222

It the same error in each case. My meteor install on windows is fine, it runs examples properly and creates projects just fine. The problem just occurs with these repos when they are clones and try to run locally on windows.

Any clues as to what could be causing it?

**Comment by laverdet** [comment]
No idea. `throw` is a very common statement in javascript, and there's no reason that shouldn't work. Something is very wrong with your node or meteor installation if that's not working.

**Comment by sonicviz** [comment]
But that's just it...My meteor install on windows is fine, it creates and runs examples properly and run other projects just fine. Ditto for node projects.

Don't you have anything more practical to troubleshoot the issue with than the old "it must be your computer that's broken" line? Logically if "Something is very wrong with your node or meteor installation if that's not working." then I would be able to run anything.

**Comment by laverdet** [comment]
What happens if you try and run:

```js
try {
  throw new Error;
} catch (err) {
  console.log(err);
}
```

**Comment by sonicviz** [comment]
G:\Meteor Projects\meteor-boilerplate-differential>meteor --allow-incompatible-update
[[[[[ ~\G\Meteor Projects\meteor-boilerplate-differential ]]]]]

=> Started proxy.
=> Started MongoDB.
[Error]ding local packages                   \
   Starting your app                         /

and hangs on "starting your app"

**Comment by laverdet** [comment]
Now that I think about it, it doesn't sound like the parser is complaining that `future.js` isn't parsing, the error is coming from a consumer of fibers -- some other library. But the stack trace is being lost somehow. Really doesn't sound like an issue in fibers but I'll try and help you out.

If I were troubleshooting this the first thing I would do is try opening that file in a text editor and right above `throw(ex)` do this:
```js
console.log(ex.stack);
console.trace();
```

I'm not even sure where meteor's console output goes, I've never used it. If you don't get any extra information what I would do next is write it to a file:
```js
var fs = require('fs');
var stack = {};
Error.captureStackTrace(stack);
fs.writeFileSync('c:\\log.txt', ex.stack+ '\r\n'+ stack.stack);
```

Then see what's in `c:\log.txt`

**Comment by sonicviz** [comment]
Thanks for the help!

This dumped out a lot more info:
G:\Meteor Projects\meteor-boilerplate-differential>meteor --allow-incompatible-update
[[[[[ ~\G\Meteor Projects\meteor-boilerplate-differential ]]]]]

=> Started proxy.
=> Started MongoDB.
SyntaxError: Unexpected token                \
    at Object.parse (native)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:692:31
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:680:7)
    at [object Object]._.extend.initFromPath (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:606:17)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack-cache.js:173:21
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack-cache.js:166:22)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack-cache.js:63:14
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\package-map.js:50:7
    at Function._.each._.forEach (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\package-map.js:42:7)
    at [object Object]._.extend.buildLocalPackages (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack-cache.js:62:24)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:698:25
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._buildLocalPackages (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:697:18)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:221:10)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:520:29
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at bundleApp (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:519:31)
    at [object Object]._.extend._runOnce (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:591:35)
    at [object Object]._.extend._fiber (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:821:28)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:402:12
Trace
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:237:37
    at process._tickCallback (node.js:442:13)
[Error]
Terminate batch job (Y/N)?
^C
G:\Meteor Projects\meteor-boilerplate-differential>

**Comment by laverdet** [comment]
Ok.. so now you look at the stack trace :)

The first thing there is isopack.js:692

I don't have meteor installed but I can see what's happening here: https://github.com/meteor/meteor/blob/master/tools/isopack.js

```js
      var unibuildJson = JSON.parse(
        files.readFile(files.pathJoin(dir, unibuildMeta.path)));
```

This is the line throwing the error. Now you go into that file do `console.log(files.pathJoin(dir, unibuildMeta.path))` right before the `JSON.parse()` call. That will output a file path. Whatever the file it outputs is supposed to be JSON but isn't.

**Comment by sonicviz** [comment]
aha! Thanks for the tips. Just getting my debug javascript boots on after a long time in C#;-)

/C/Users/Paul/AppData/Local/.meteor/packages/service-configuration/1.0.4/web.browser.json
/C/Users/Paul/AppData/Local/.meteor/packages/service-configuration/1.0.4/web.cordova.json
/C/Users/Paul/AppData/Local/.meteor/packages/softwarerero_accounts-t9n/1.0.9/os.json
SyntaxError: Unexpected token
    at Object.parse (native)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:693:31
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:680:7)
    at [object Object]._.extend.initFromPath (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:606:17)
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack-cache.js:173:21
    at C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)

Seems to be this os.json is the problem, but the package has no reference to it:

meteor-platform
less
accounts-password
useraccounts:bootstrap
alanning:roles
zimme:iron-router-active
cmather:handlebars-server@0.2.0
dburles:collection-helpers
reywood:publish-composite
momentjs:moment
mrt:underscore-string-latest
matb33:collection-hooks
dburles:factory
anti:fake
cunneen:mailgun
iron:router@1.0.9
yasinuslu:blaze-meta
aldeed:collection2
aldeed:autoform

hmmm.

**Comment by laverdet** [comment]
Did you try grep'ing for `os.json` in your whole source tree and finding out which tool is suppose to generate it?

**Comment by sonicviz** [comment]
os.json is just full of 
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000

**Comment by laverdet** [comment]
I meant grep the source code not file paths. Somewhere in that source tree is something that does `fs.writeFile('os.json', <whatever>)` and you have to find that line, and see why it's failing.

**Comment by sonicviz** [comment]
yes, looking now.

**Comment by sonicviz** [comment]
Couldn't find it, but solved it by brute force method: I deleted softwarerero_accounts-t9n folder and it downloaded it again when needed to build, this time seems ok.
Meteor now starts successfully!

Thanks very much for your walk through, patience, and help.

**Comment by laverdet** [comment]
Kewl
