### ISSUE TITLE
Error installing v1.0.5 on OS X 10.10.4

### ISSUE THREAD

**Issue by joarobles** [laverdet/node-fibers#237]
I'm having this error while trying to install fibers@1.0.5 on OS X 10.10.4

```
$ sudo npm install -g fibers@1.0.5
|
> fibers@1.0.5 install /usr/local/lib/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/local/lib/node_modules/fibers
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "fibers@1.0.5"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
```

But v1.0.6 installs just fine, any idea?

**Comment by sjmcdowall** [comment]
Idea -- fibers@1.0.6 is compiled for Mac OS X.  @1.0.5 is NOT so it's trying to re-compile it and  you haven't ever run Xcode so haven't agreed to the license terms so it's giving an error.

However, in reality you shouldn't NEED to compile fibers.  I don't know why they pulled 1.0.5 when its still in general use. :(

**Comment by laverdet** [comment]
Hmm I'm not sure why the 1.0.5 binaries don't work. If you really want to use 1.0.5 you can run `sudo xcodebuild -license` first and then `npm install fibers` and I think it'll build fine on your system. Or just use 1.0.6.

**Comment by sjmcdowall** [comment]
I think it's the version of node. He's on 0.12.X and I'm sure that v8 version is not 3.14 -- so it builds a new one because 1.0.5 only has support for v8 3.14.  1.0.6 should work unless he's doing a meteor project .. then I'm not sure it will.
