### ISSUE TITLE
Cant install fibers on windows 10.

### ISSUE THREAD

**Issue by DavidBarishev** [laverdet/node-fibers#250]
I tried installing fibers with no luck
```
D:\Projects\Lounge\Lounge>npm install fibers --save

> fibers@1.0.7 install D:\Projects\Lounge\Lounge\node_modules\fibers
> node build.js || nodejs build.js


D:\Projects\Lounge\Lounge\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not fi
nd WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versio
n number. [D:\Projects\Lounge\Lounge\node_modules\fibers\build\fibers.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\Projects\Lounge\Lou
nge\node_modules\fibers\build\fibers.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\Projects\Lounge\Lounge\node_modules\fibers
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN EPACKAGEJSON Lounge@0.0.0 No repository field.
npm WARN EPACKAGEJSON Lounge@0.0.0 No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fibers" "--save"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\Lounge\Lounge\npm-debug.log
```

Im using visual studios 2015 , windows 10 64 bit . node v 4.1.0  npm 3.3.4.<br>
I have compilers for c++ for 64 and 32 bit (2010-2015) and python 2.7.10.
Am im doing something wrong ? or what addition software should i install ?

**Comment by sjmcdowall** [comment]
http://blogs.msdn.com/b/vcblog/archive/2015/07/24/setup-changes-in-visual-studio-2015-affecting-c-developers.aspx

Did you install the optional C++ stuff? If so is your path including them for command line building?

**Comment by DavidBarishev** [comment]
Yup , i needed to install all the other staff , thank you
