### ISSUE TITLE
Failed to install Fibers

### ISSUE THREAD

**Issue by zjhzxhz** [laverdet/node-fibers#254]
Here's the error log.

```
➜  GoingOn git:(master) ✗ npm install node-fibers
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-fibers"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-fibers
npm ERR! 404 
npm ERR! 404 'node-fibers' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiehaozhe/Development/JavaScript/GoingOn/npm-debug.log
```

**Comment by zjhzxhz** [comment]
Here's the content of npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-fibers' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node-fibers
8 silly fetchNamedPackageData node-fibers
9 silly mapToRegistry name node-fibers
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/node-fibers
13 verbose request uri https://registry.npmjs.org/node-fibers
14 verbose request no auth needed
15 info attempt registry request try #1 at 23:34:49
16 verbose request id 3777441530d63e02
17 http request GET https://registry.npmjs.org/node-fibers
18 http 404 https://registry.npmjs.org/node-fibers
19 verbose headers { 'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=0',
19 verbose headers   'content-length': '2',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Sat, 07 Nov 2015 15:34:50 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-sjc3128-SJC',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1446910490.278998,VS0,VE87' }
20 silly get cb [ 404,
20 silly get   { 'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=0',
20 silly get     'content-length': '2',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Sat, 07 Nov 2015 15:34:50 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-sjc3128-SJC',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1446910490.278998,VS0,VE87' } ]
21 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/node-fibers
21 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
21 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
21 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
21 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
21 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
21 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
21 silly fetchPackageMetaData     at emitOne (events.js:82:20)
21 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
21 silly fetchPackageMetaData  error for node-fibers { [Error: Registry returned 404 for GET on https://registry.npmjs.org/node-fibers] pkgid: 'node-fibers', statusCode: 404, code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/node-fibers
27 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
27 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
27 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
27 verbose stack     at emitTwo (events.js:87:13)
27 verbose stack     at Request.emit (events.js:172:7)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
27 verbose stack     at emitOne (events.js:82:20)
27 verbose stack     at Request.emit (events.js:169:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
28 verbose statusCode 404
29 verbose pkgid node-fibers
30 verbose cwd /Users/xiehaozhe/Development/JavaScript/GoingOn
31 error Darwin 15.0.0
32 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-fibers"
33 error node v5.0.0
34 error npm  v3.3.6
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/node-fibers
36 error 404
36 error 404 'node-fibers' is not in the npm registry.
36 error 404 You should bug the author to publish it (or use the name yourself!)
36 error 404
36 error 404 Note that you can also install from a
36 error 404 tarball, folder, http url, or git url.
37 verbose exit [ 1, true ]
```

**Comment by sjmcdowall** [comment]
This maybe obvious but isn't the proper command:

npm install fibers

not node-fibers
?

**Comment by laverdet** [comment]
lol
