### ISSUE TITLE
Cant install fibers on OS X

### ISSUE THREAD

**Issue by activestylus** [laverdet/node-fibers#255]
Was trying to install meteor when i got this error. I then tried to install fibers manually and same error popped up. I'm on node 0.11.11

```
npm install -g fibers
npm http GET https://registry.npmjs.org/fibers
npm http 200 https://registry.npmjs.org/fibers
npm http GET https://registry.npmjs.org/fibers/-/fibers-1.0.7.tgz
npm http 200 https://registry.npmjs.org/fibers/-/fibers-1.0.7.tgz

> fibers@1.0.7 install /usr/local/lib/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:72:
/usr/include/sys/unistd.h:204:40: error: C++ requires a type specifier for all
      declarations
int     fchownat(int, const char *, uid_t, gid_t, int)  __OSX_AVAILABLE_...
                                           ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:429:33: error: unknown type name 'gid_t'
int      chown(const char *, uid_t, gid_t);
                                    ^
/usr/include/unistd.h:444:1: error: unknown type name 'gid_t'
gid_t    getegid(void);
^
/usr/include/unistd.h:446:1: error: unknown type name 'gid_t'
gid_t    getgid(void);
^
/usr/include/unistd.h:450:21: error: C++ requires a type specifier for all
      declarations
int      getgroups(int, gid_t []);
                        ^
/usr/include/unistd.h:469:13: error: unknown type name 'gid_t'
int      setgid(gid_t);
                ^
/usr/include/unistd.h:565:34: error: unknown type name 'gid_t'
int      lchown(const char *, uid_t, gid_t) __DARWIN_ALIAS(lchown);
                                     ^
/usr/include/unistd.h:591:15: error: C++ requires a type specifier for all
      declarations
int      setregid(gid_t, gid_t) __DARWIN_ALIAS(setregid);
                  ^
/usr/include/unistd.h:591:22: error: unknown type name 'gid_t'
int      setregid(gid_t, gid_t) __DARWIN_ALIAS(setregid);
                         ^
/usr/include/unistd.h:598:1: error: unknown type name 'useconds_t'; did you mean
      'node::useconds_t'?
useconds_t       ualarm(useconds_t, useconds_t);
^
/usr/include/sys/_types/_useconds_t.h:30:29: note: 'node::useconds_t' declared
      here
typedef __darwin_useconds_t     useconds_t;
                                ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:598:20: error: unknown type name 'useconds_t'; did you
      mean 'node::useconds_t'?
useconds_t       ualarm(useconds_t, useconds_t);
                        ^
/usr/include/sys/_types/_useconds_t.h:30:29: note: 'node::useconds_t' declared
      here
typedef __darwin_useconds_t     useconds_t;
                                ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:598:32: error: unknown type name 'useconds_t'; did you
      mean 'node::useconds_t'?
useconds_t       ualarm(useconds_t, useconds_t);
                                    ^
/usr/include/sys/_types/_useconds_t.h:30:29: note: 'node::useconds_t' declared
      here
typedef __darwin_useconds_t     useconds_t;
                                ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:599:13: error: unknown type name 'useconds_t'; did you
      mean 'node::useconds_t'?
int      usleep(useconds_t) __DARWIN_ALIAS_C(usleep);
                ^
/usr/include/sys/_types/_useconds_t.h:30:29: note: 'node::useconds_t' declared
      here
typedef __darwin_useconds_t     useconds_t;
                                ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:619:25: error: unknown type name 'gid_t'
int      fchown(int, uid_t, gid_t);
                            ^
/usr/include/unistd.h:622:14: error: unknown type name 'gid_t'
int      setegid(gid_t);
                 ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:633:
/usr/include/sys/select.h:114:19: error: unknown type name 'fd_set'; did you
      mean 'node::fd_set'?
int      pselect(int, fd_set * __restrict, fd_set * __restrict,
                      ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:633:
/usr/include/sys/select.h:114:40: error: unknown type name 'fd_set'; did you
      mean 'node::fd_set'?
int      pselect(int, fd_set * __restrict, fd_set * __restrict,
                                           ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:633:
/usr/include/sys/select.h:115:3: error: unknown type name 'fd_set'; did you mean
      'node::fd_set'?
                fd_set * __restrict, const struct timespec * __restrict,
                ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:3:
In file included from /usr/include/c++/4.2.1/vector:65:
In file included from /usr/include/c++/4.2.1/bits/functexcept.h:41:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:633:
In file included from /usr/include/sys/select.h:129:
/usr/include/sys/_select.h:39:18: error: unknown type name 'fd_set'; did you
      mean 'node::fd_set'?
int      select(int, fd_set * __restrict, fd_set * __restrict,
                     ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/homebass/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/Users/homebass/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/local/lib/node_modules/fibers
gyp ERR! node -v v0.11.11
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
Build failed
sh: nodejs: command not found
npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/Users/homebass/local/bin/npm" "install" "-g" "fibers"
npm ERR! cwd /Users/homebass/Code/src
npm ERR! node -v v0.11.11
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/homebass/Code/src/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sjmcdowall** [comment]
Well first off -- how EXACTLY are you trying to install meteor on Mac OS X?  Meteor bundles it's own compiled node and fibers for Mac, so the above should never happen if you use the common download etc.  Also, meter only supports (with 1.2) node 0.10.40 .. but again, it bundles it's own node with the overall package ... so it should be a pretty darn easy install .. 

So it should be as easy as:

curl https://install.meteor.com/ | sh

with proper permissions ...

**Comment by activestylus** [comment]
I was trying to simply install meteor with npm install when ti blew up on me. The curl command worked just fine so thanks for that
