### ISSUE TITLE
Cannot install Fibers 1.0.5

### ISSUE THREAD

**Issue by williamvasconcelos** [laverdet/node-fibers#288]
Trying to install and i got this error:

OS: Mac El Capitan 10.11.4 (15E65)
NODE: 4.4.4
NODE-GYP: 3.3.1
```
Mobile:node-fibers-1.0.5 mobileserver$ npm install
npm WARN package.json fibers@1.0.5 No license field.

> fibers@1.0.5 install /Users/mobileserver/node-fibers-1.0.5
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:132:44: error: too many arguments to function call, expected at most 2, have 4
                return Signature::New(isolate, receiver, argc, argue)
                       ~~~~~~~~~~~~~~                    ^~~~~~~~~~
/Users/mobileserver/.node-gyp/4.4.4/include/node/v8.h:4675:3: note: 'New' declared here
  static Local<Signature> New(
  ^
../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in namespace 'v8'; did you mean simply 'SetResourceConstraints'?
                v8::SetResourceConstraints(isolate, constraints);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                SetResourceConstraints
../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
        void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
             ^
../src/fibers.cc:428:6: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                                        delete data;
                                        ^
                                              []
../src/fibers.cc:423:19: note: allocated with 'new[]' here
                                void** data = new void*[2];
                                              ^
1 warning and 2 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/mobileserver/node-fibers-1.0.5
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! nam  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with nam itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mobileserver/node-fibers-1.0.5/npm-debug.log
```;

**Comment by sjmcdowall** [comment]
Fibers 1.0.5 is an ancient old version -- let me guess.. Meteor? What exactly are you trying to do? The meteor version ONLY works with the special version of node 0.10.40 (?) or there abouts.  If you are not doing Meteor you should use the latest Fibers
