### ISSUE TITLE
Jenkins failing on version 1.0.15

### ISSUE THREAD

**Issue by cadwmaster** [laverdet/node-fibers#313]
Hi, yesterday some of our building process were failing after the npm update to 1.0.15, this is the error log:

```
make: Entering directory `/home/ec2-user/workspace/XProject/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Leaving directory `/home/ec2-user/workspace/XProject/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_5.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.1.17-22.30.amzn1.x86_64
gyp ERR! command "/home/ec2-user/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_5.8.0/bin/node" "/home/ec2-user/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_5.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/ec2-user/workspace/XProject/node_modules/fibers
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-gyp exited with code: 1



npm ERR! Linux 4.1.17-22.30.amzn1.x86_64
npm ERR! argv "/home/ec2-user/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_5.8.0/bin/node" "/home/ec2-user/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_5.8.0/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
```

Btw, version 1.0.14 works great

**Comment by kyleBeikirch** [comment]
We are having a similar issue with 1.0.15 

```[INFO]   CXX(target) Release/obj.target/fibers/src/fibers.o
[ERROR] In file included from /home/jenkins/.node-gyp/5.5.0/include/node/node.h:42,
[ERROR]                  from ../src/coroutine.h:1,
[ERROR]                  from ../src/fibers.cc:1:
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:336: error: expected unqualified-id before 'using'
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:353: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:360: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:364: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:430: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: At global scope:
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:469: error: expected unqualified-id before 'using'
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In constructor 'v8::Global<T>::Global()':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:794: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In constructor 'v8::Global<T>::Global(v8::Global<T>&&)':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:819: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:831: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: At global scope:
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:856: error: expected unqualified-id before 'using'
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:1093: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:1099: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:3204: error: 'nullptr' was not declared in this scope
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
[ERROR] /home/jenkins/.node-gyp/5.5.0/include/node/v8.h:7154: error: 'nullptr' was not declared in this scope
[ERROR] ../src/fibers.cc: At global scope:
[ERROR] ../src/fibers.cc:70: error: 'Handle' has not been declared
[ERROR] ../src/fibers.cc:70: error: expected ',' or '...' before '<' token
[ERROR] ../src/fibers.cc: In function 'void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)':
[ERROR] ../src/fibers.cc:71: error: 'handle' was not declared in this scope
[ERROR] ../src/fibers.cc: At global scope:
[ERROR] ../src/fibers.cc:83: error: variable or field 'SetInternalPointer' declared void
[ERROR] ../src/fibers.cc:83: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:83: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:83: error: 'handle' was not declared in this scope
[ERROR] ../src/fibers.cc:83: error: expected primary-expression before 'int'
[ERROR] ../src/fibers.cc:83: error: expected primary-expression before 'void'
[ERROR] ../src/fibers.cc:87: error: template declaration of 'void* uni::GetInternalPointer'
[ERROR] ../src/fibers.cc:87: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:87: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:87: error: 'handle' was not declared in this scope
[ERROR] ../src/fibers.cc:87: error: expected primary-expression before 'int'
[ERROR] ../src/fibers.cc:92: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:97: error: variable or field 'Return' declared void
[ERROR] ../src/fibers.cc:97: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:97: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:97: error: 'handle' was not declared in this scope
[ERROR] ../src/fibers.cc:97: error: expected primary-expression before 'const'
[ERROR] ../src/fibers.cc:101: error: variable or field 'Return' declared void
[ERROR] ../src/fibers.cc:101: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:101: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:101: error: 'handle' was not declared in this scope
[ERROR] ../src/fibers.cc:101: error: expected primary-expression before 'info'
[ERROR] ../src/fibers.cc:109: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:113: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:117: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:121: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:125: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:129: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:133: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:137: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:147: error: expected constructor, destructor, or type conversion before '<' token
[ERROR] ../src/fibers.cc:319: error: expected ';' before '(' token
[ERROR] ../src/fibers.cc:325: error: expected ';' before 'Fiber'
[ERROR] ../src/fibers.cc:325: error: expected ')' before '<' token
[ERROR] ../src/fibers.cc:591: error: ISO C++ forbids declaration of 'Handle' with no type
[ERROR] ../src/fibers.cc:591: error: expected ';' before '<' token
[ERROR] ../src/fibers.cc:829: error: expected ';' at end of input
[ERROR] ../src/fibers.cc:829: error: expected '}' at end of input
[ERROR] ../src/fibers.cc: In static member function 'static void Fiber::DestroyOrphans()':
[ERROR] ../src/fibers.cc:406: error: 'Deref' is not a member of 'uni'
[ERROR] ../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const uni::Arguments&)':
[ERROR] ../src/fibers.cc:428: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:428: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:428: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:430: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:430: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:430: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:432: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:432: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:432: error: 'argv' was not declared in this scope
[ERROR] ../src/fibers.cc:433: error: 'Deref' is not a member of 'uni'
[ERROR] ../src/fibers.cc:433: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:436: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:436: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:436: error: 'fn' was not declared in this scope
[ERROR] ../src/fibers.cc:436: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:436: error: '::Cast' has not been declared
[ERROR] ../src/fibers.cc:437: error: 'GetCurrentContext' is not a member of 'uni'
[ERROR] ../src/fibers.cc:438: error: no matching function for call to 'Return(v8::Local<v8::Object>, const v8::FunctionCallbackInfo<v8::Value>&)'
[ERROR] ../src/fibers.cc:438: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Run(const uni::Arguments&)':
[ERROR] ../src/fibers.cc:446: error: 'Unwrap' was not declared in this scope
[ERROR] ../src/fibers.cc:452: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:452: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:452: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:454: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:454: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:454: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:462: error: 'RunFiber' was not declared in this scope
[ERROR] ../src/fibers.cc:465: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:465: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:465: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:475: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
[ERROR] ../src/fibers.cc:477: error: 'Undefined' is not a member of 'uni'
[ERROR] ../src/fibers.cc:481: error: 'class Fiber' has no member named 'ReturnYielded'
[ERROR] ../src/fibers.cc:481: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::ThrowInto(const uni::Arguments&)':
[ERROR] ../src/fibers.cc:488: error: 'Unwrap' was not declared in this scope
[ERROR] ../src/fibers.cc:491: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:491: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:491: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:493: error: 'Undefined' is not a member of 'uni'
[ERROR] ../src/fibers.cc:495: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
[ERROR] ../src/fibers.cc:497: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:497: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:497: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:501: error: 'class Fiber' has no member named 'ReturnYielded'
[ERROR] ../src/fibers.cc:501: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Reset(const uni::Arguments&)':
[ERROR] ../src/fibers.cc:509: error: 'Unwrap' was not declared in this scope
[ERROR] ../src/fibers.cc:512: error: 'Undefined' is not a member of 'uni'
[ERROR] ../src/fibers.cc:512: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:514: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:514: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:514: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:516: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:516: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:516: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:524: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:524: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:524: error: 'val' was not declared in this scope
[ERROR] ../src/fibers.cc:524: error: 'Deref' is not a member of 'uni'
[ERROR] ../src/fibers.cc:527: error: 'ThrowException' is not a member of 'uni'
[ERROR] ../src/fibers.cc:527: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc:529: error: return-statement with a value, in function returning 'void'
[ERROR] ../src/fibers.cc: In member function 'void Fiber::UnwindStack()':
[ERROR] ../src/fibers.cc:546: error: 'Handle' was not declared in this scope
[ERROR] ../src/fibers.cc:546: error: expected primary-expression before '>' token
[ERROR] ../src/fibers.cc:546: error: 'NewLatin1String' is not a member of 'uni'
[ERROR] ../src/fibers.cc:547: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
[ERROR] ../src/fibers.cc:548: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
[ERROR] ../src/fibers.cc:561: error: 'Undefined' is not a member of 'uni'
[ERROR] ../src/fibers.cc: At global scope:
[ERROR] ../src/fibers.cc:586: error: expected unqualified-id at end of input
[ERROR] make: *** [Release/obj.target/fibers/src/fibers.o] Error 1 ```
1.0.14 worked for us as well

**Comment by laverdet** [comment]
You guys will need to either upgrade to node 6 or install a compiler (@kyleBeikirch you actually do have a compiler installed, it's just terribly broken). I'm no longer including pre-built binaries for node 5, as it is no longer maintained by the node developers (node 6 took its place). For future reference odd-numbered versions of node will receive very little support in the long term. You can find more information here: https://github.com/nodejs/LTS

You also have the option to just stay on fibers 1.0.14.
