### ISSUE TITLE
Unable to install with node 7

### ISSUE THREAD

**Issue by monolithed** [laverdet/node-fibers#319]
```
13:28:03 npm ERR! Linux 4.4.0-31-generic
13:28:03 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
13:28:03 npm ERR! node v7.0.0
13:28:03 npm ERR! npm  v3.10.8
13:28:03 npm ERR! code ELIFECYCLE
13:28:03 
13:28:03 npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
13:28:03 npm ERR! Exit status 1
13:28:03 npm ERR! 
13:28:03 npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
```

How to fix that?

**Comment by brianhhq** [comment]
I can install firbers in v7.0.0 in mac but not ubuntu

**Comment by alippai** [comment]
It doesn't work on Windows, on Arch linux with nvm it works.

**Comment by laverdet** [comment]
Please read the rest of the error log. There are instructions on how to fix this error if you scroll up a little bit.

**Comment by monolithed** [comment]
@laverdet, what do you mean? The rest of error log is an instruction how to report one.

**Comment by laverdet** [comment]
```
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++
```

**Comment by monolithed** [comment]
Hm, I haven't seen these instruction before. Thanks! I will try again tomorrow

**Comment by megamindbrian** [comment]
I don't want to compile fibers, I just want to run npm install and everything works. ;)

**Comment by laverdet** [comment]
@megamindbrian node-gyp doesn't require fibers, whatever you're trying to install does.

The problem is that for odd-numbered versions of node they are allowed to change the [ABI](https://en.wikipedia.org/wiki/Application_binary_interface) with a minor semvar. Take node 7.x for example, they've already updated v8 three times. For each of these versions I would need to push a new version of fibers to npm, and each version of course needs to be compiled for Linux, OS X, and Windows. Then when node 8.x is released node 6.x becomes LTS and node 7.x is supported by the node team for like a week before they deprecate it completely. Ok so now when I push a bug fix and don't compile it for all the random node 7.x versions I used to support I end up breaking someone's app and they yell at me.

It's just a lot easier to say "I only support binary releases for the last two even-numbered versions". I've made it as easy as I can for anyone to compile it, you just have to install one thing first. Basically it's a lot that you're asking of me and not much that I'm asking of you~

**Comment by megamindbrian** [comment]
How do I make your life easier?
What if there is a list to check like this?

```
try {
// get pre-built for release versions
// test load the module
} catch (e) {
// build with native build tools
}
```

Isn't compiling with different dependencies something Travis-CI is supped
to do?  I was thinking to force this upon repos by checking out every
version of common stacks and producing a grid of broken versions.  Not sure
if there is some way to do that with modern tools already?

**Comment by laverdet** [comment]
Sorry I'm not really sure what you're asking..

**Comment by LKay** [comment]
Any update on how to fix that? This is driving me crazy for some time now. I'm runing `npm install` in docker using official node image `node:6` (also tried bunch of others including, 7, 8, alpine builds). I did install all dependencies `gcc`, `g++~`, `build-essential` etc. but still fails.

**Comment by sjmcdowall** [comment]
Do you have any debug output?  

Also — how about just sticking with Node 8 for now — and sending the log information that is generated back when you try to install fibers?  And all the command lines, etc. 

A vanilla Node 8 should use the pre-compiled binaries ..

**Comment by laverdet** [comment]
If he's using Alpine Linux (which it seems like he might be?) then he can't use the precompiled binaries because Alpine uses musl libc instead of gnu libc. The install process will detect this an invoke the compiler.

@LKay logs would help us troubleshoot your issue, "it fails" isn't very good information.

**Comment by sjmcdowall** [comment]
Ah good point and “Docker” should have been a hint since a lot of people use Alpine Linux for that !

Although it seems to me that there were a few other people using Alpine Linux for Fibers and they got it running — so maybe he can look in the “history” of issues for others w/ Alpine Linux (assuming that IS the case)

**Comment by LKay** [comment]
I am not using Alpine based image, even though I also tried these... I'm using images based on Debian Jessie: `node:6`, `node:7`, `node:8`. The command I run before hitting `npm i` are just like in the instructions:

```
RUN apt-get update \
  && apt-get install -y \
    python \
    gcc \
    make \
    g++ \
    build-essential \
  && npm i -g node-gyp
```

This is ridiculous!

Here are the logs:
```
npm info lifecycle fibers@1.0.15~install: fibers@1.0.15

> fibers@1.0.15 install /home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers
> node build.js || nodejs build.js
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v7.7.1/node-v7.7.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.7.1/node-v7.7.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.7.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.7.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/$WORKSPACE/.node-gyp/7.7.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/$WORKSPACE/.node-gyp/7.7.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build'
make: *** No rule to make target '../ORKSPACE/.node-gyp/7.7.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.44-39.55.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/$WORKSPACE/.node-gyp/7.7.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/$WORKSPACE/.node-gyp/7.7.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build'
make: *** No rule to make target '../ORKSPACE/.node-gyp/7.7.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.44-39.55.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/node_modules/fibers
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
npm info lifecycle fibers@1.0.15~install: Failed to exec install script
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN wdio-webpack-service@1.0.1 requires a peer of webpack@1.x but none was installed.
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.
npm ERR! Linux 4.4.44-39.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/workspace/project_master-IYJBXOBN6PLJAQ6VMXTFIUD6MGMBWPTFQ6YBXO4BVGWWZJARHSNA/npm-debug.log
```

**Comment by megamindbrian** [comment]
sudo in your RUN command or ensure USER root comes before it. Whatever USER
is last is the user your script assumes with CMD and ENTRYPOINTs.

Does that help?

**Comment by gedeagas** [comment]
Hey, are you able to solve the issue @LKay

**Comment by LKay** [comment]
Not really. Workaround for me is to install `node-gyp` globally along with build essentials on every docker container build and compile everything when container image is build.

**Comment by megamindbrian** [comment]
I think something is failing during a fresh install.y coworker just had
this error, said he already ran windows-build-tools as root.
3640 error path
C:\Data\ecommerce2dev\ecommerce2\node_modules\fsevents\node_modules\ansi-regex\package.json
3641 error code EPERM
3642 error errno -4048
3643 error syscall unlink
3644 error Error: EPERM: operation not permitted, unlink
'C:\Data\ecommerce2dev\ecommerce2\node_modules\fsevents\node_modules\ansi-regex\package.json'
3644 error     at Error (native)
3644 error  { Error: EPERM: operation not permitted, unlink
'C:\Data\ecommerce2dev\ecommerce2\node_modules\fsevents\node_modules\ansi-regex\package.json'
3644 error     at Error (native)
3644 error   stack: 'Error: EPERM: operation not permitted, unlink
\'C:\\Data\\ecommerce2dev\\ecommerce2\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json\'\n
   at Error (native)',
3644 error   errno: -4048,
3644 error   code: 'EPERM',
3644 error   syscall: 'unlink',
3644 error   path:
'C:\\Data\\ecommerce2dev\\ecommerce2\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json'
}
3645 error Please try running this command again as root/Administrator.

**Comment by sjmcdowall** [comment]
May I ask an obvious question — why Node 7?  It’s an unsupported node version etc. etc.  Node V8.5 LTS just came out — why not try using that node?  THere are some nice docker images already for running node applications that use node v8.5 .. 

Just a suggestion .. doesn’t seem like node v7 really buys you anything?

**Comment by laverdet** [comment]
@sjmcdowall from what I can gather there's at least three different issues being discussed on this thread, but the answer to all of them are essentially "install a compiler" or "fix your compiler".

1) Originally the issue was about node v7, I don't ship binaries for odd-numbered binaries for reasons already mentioned.
2) @LKay was having issues with docker, specifically Alpine Linux. Alpine uses a different version of libc which needs some different compiler flags, so I don't ship binaries for that one either. He's already got his build working correctly, so that's good.
3) @megamindbrian just copy/pasted error logs from `fsevents` which isn't my module, but it also has a compilation stage so I can only assume he has build issues too. The solution there is to follow the instructions in the [node-gyp README](https://github.com/nodejs/node-gyp).

The native module toolchain for nodejs has some coverage gaps which can cause issues like this that are difficult to troubleshoot if you've never needed to compile anything.

**Comment by megamindbrian** [comment]
My problem is a lot of parts of the eco-system are built on top of these
packages.  The pattern is causing problems for a lot of people and isn't
straight forward to get installed because of the other reasons you
mentioned.  So it doesn't matter which logs or where the instructions are,
my search for help on this error led me here.

**Comment by laverdet** [comment]
It's not fair to say it doesn't matter "which logs" when you posted logs from a totally different package. The github page for `fsevents` is [over here](https://github.com/strongloop/fsevents). Regardless, there's very little either I or the maintainer of that package can do about gaps in compiler coverage except help point you in the right direction of the documentation relevant to you.

The node team is working on something called N-API which will help mitigate some of these issues, though in the case of fibers it won't help at all. nodejs is still a relatively new platform and native modules are not a priority for the team so you just have to deal with a little extra legwork.

**Comment by megamindbrian** [comment]
It's the wrong pattern to use.  Whether its fs-events or node-gyp, this
pattern of installing something and then having to recompile what you just
"installed" is wrong.  Apt-get solved this problem a long time ago, I can
go and download something with apt without having to rebuild my entire
kernel.  Node needs to use these lessons.  I still don't understand why you
can't compile for every version of node, I thought the whole point of CI is
to handling compiling automatically.  Compiling should be second nature,
not something that forces you to make design trade-offs.

**Comment by laverdet** [comment]
apt is a package manager designed with binary applications explicitly in mind. npm is made first and foremost for pure-JS libraries that don't need a compilation stage; native module support is added as an afterthought. apt is also 12 years older than npm. Also apt only supports likes two Linux distributions whereas nodejs supports Windows, OS X, most (all?) Linux distributions, and a bunch of other platforms like SunOS and BSD flavors. The infrastructure and tool support just isn't there for me to plug in to. Also I'm not in charge of nodejs, npm or node-gyp so there's not much I can do for you anyway. Most users can use this package straight off npm with no problems and those that can't usually just need to install a package or two to get it to work.

**Comment by laverdet** [comment]
And speaking of all the problems that apt has solved.. if I run `apt-get install nodejs` right now on a new Ubuntu machine it installs version v4.2.6 (released January 2016) and names the binary `nodejs` instead of `node` which breaks pretty much everything. If you want to install a version of node released in the past year you have to pipe `curl` into `sudo bash`. I'm not really sure that's the example we should be setting.

**Comment by BenGlasser** [comment]
can't compile fibers@1.0.15

OS X: 10.14
Node: v10.13.0
npm: 6.4.1

```
> fibers@1.0.15 install /Users/$USER/git/voyager/node_modules/wdio-sync/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:122:64: error: too few arguments to function call, expected at least 3, have 2
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                       ~~~~~~~~~~~~~~~~~~~~~~                                ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:2802:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
../src/fibers.cc:126:64: error: too few arguments to function call, expected at least 3, have 2
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                       ~~~~~~~~~~~~~~~~~~~~~~                                ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:2802:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
../src/fibers.cc:406:24: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                                        String::Utf8Value stack(uni::Deref(that.isolate, fatal_stack));
                                                          ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:433:80: error: no matching member function for call to 'NewInstance'
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context',
      but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/fibers.cc:621:14: error: no matching constructor for initialization of 'v8::TryCatch'
                                TryCatch try_catch;
                                         ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:8536:12: note: candidate constructor not viable: requires single argument
      'isolate', but no arguments were provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:8656:3: note: candidate constructor not viable: requires 1 argument, but 0 were
      provided
  TryCatch(const TryCatch&) = delete;
  ^
../src/fibers.cc:628:13: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
                                Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));
                                        ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:1255:10: note: 'Compile' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:741:34: error: no matching member function for call to 'ToNumber'
                        Coroutine::pool_size = value->ToNumber()->Value();
                                               ~~~~~~~^~~~~~~~
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/fibers.cc:793:72: error: too few arguments to function call, expected at least 3, have 2
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                        ~~~~~~~~~~~~~~~                                                     ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:3348:3: note: 'SetAccessor' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
  ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/fibers.cc:794:63: error: no viable conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka
      'void (Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') to 'Local<v8::Name>'
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                   ^~~~~~~~~~~
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:204:7: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka 'void (Local<v8::String>,
      const PropertyCallbackInfo<v8::Value> &)') to 'const v8::Local<v8::Name> &' for 1st argument
class Local {
      ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:204:7: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'uni::FunctionType (Local<v8::String>, const uni::GetterCallbackInfo &)' (aka 'void (Local<v8::String>,
      const PropertyCallbackInfo<v8::Value> &)') to 'v8::Local<v8::Name> &&' for 1st argument
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:208:13: note: candidate template ignored: could not match
      'Local<type-parameter-0-0>' against 'void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value> &)'
  V8_INLINE Local(Local<S> that)
            ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:3349:43: note: passing argument to parameter 'name' here
      Local<Context> context, Local<Name> name,
                                          ^
../src/fibers.cc:795:84: error: too few arguments to function call, expected at least 3, have 2
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                        ~~~~~~~~~~~~~~~                                                                 ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:3348:3: note: 'SetAccessor' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
  ^
/Users/bglasser/.node-gyp/10.13.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/fibers.cc:1:
In file included from ../src/coroutine.h:1:
In file included from /Users/bglasser/.node-gyp/10.13.0/include/node/node.h:63:
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:215:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/bglasser/.node-gyp/10.13.0/include/node/v8.h:169:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../src/fibers.cc:794:20: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>'
      requested here
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                        ^
2 warnings and 9 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/bglasser/git/voyager/node_modules/wdio-sync/node_modules/fibers
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN enoent ENOENT: no such file or directory, open '/Users/bglasser/git/voyager/node_modules/flat-cache/node_modules/del/package.json'
npm WARN html-webpack-template@5.6.2 requires a peer of html-webpack-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN karma-webpack@3.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-currency-input@1.3.6 requires a peer of prop-types@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-currency-input@1.3.6 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-currency-input@1.3.6 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-event-listener@0.6.4 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form@7.4.2 requires a peer of react-redux@^4.3.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bglasser/.npm/_logs/2018-12-04T22_17_33_445Z-debug.log```

**Comment by sjmcdowall** [comment]
It's rare to have to compile Fibers on Mac OS X .. why are you trying this? 

Have you checked the compatibility and tried a pre-built binary? 

Just sort of odd

**Comment by tcf909** [comment]
I use fibers on Mac every day, but version 1.x is very old. Use the latest
3.x and you will be fine.

**Comment by HeaventTso** [comment]
Maybe try npm install fibers@3.1.0
I use it on Win7 it's work
