### ISSUE TITLE
Fibers was compiled against a different Node.js

### ISSUE THREAD

**Issue by Heziode-dev** [laverdet/node-fibers#338]
When I upgrade my Node and rebuild fibers after message warning I obtained this error :

```
 ▸ node quick-test.js 
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/path/to/project/node_modules/fibers/bin/linux-x64-51/fibers.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/project/node_modules/fibers/fibers.js:24:37)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

I use meteor in my project.
Version :
- Node : v7.8.0
- Meteor : 1.4.3.2

**Comment by Heziode-dev** [comment]
Fix when I use build from source repo, no npm install.
