### ISSUE TITLE
New version is breaking asycnawait on AWS Lambda

### ISSUE THREAD

**Issue by aznoorani-buckit** [laverdet/node-fibers#343]
{
  "errorMessage": "Missing binary. See message above.",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/asyncawait/src/fibers.js:1:75)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)"
  ]
}

module initialization error: Error
at Object.<anonymous> (/var/task/node_modules/asyncawait/node_modules/fibers/fibers.js:20:9)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/asyncawait/src/fibers.js:1:75)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

It seems new version is causing the fibers object files to be rebuilt using CXX or g++ which may be breaking this.

**Comment by laverdet** [comment]
If you are using node v4.x please make sure you have fibers@1.0.15 selected. If you are using node v6.x or above then please reinstall fibers.
