### ISSUE TITLE
quick-test.js fails

### ISSUE THREAD

**Issue by holiber** [laverdet/node-fibers#356]
```
node node_modules/fibers/quick-test.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\alex\projects\xxx-project\node_modules\fibers\bin\win32-x64-51\fibers.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\alex\projects\streamlabs-obs\node_modules\fibers\fibers.js:24:38)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
The file in win32-x64-51 directory exists

OS - win10,

```
$ node -v
v7.9.0
```

I tried to reinstall fibers several times

**Comment by holiber** [comment]
I upgraded to node `v8.9.1` and now it works. So the issue is actual for  `v7.9.0`

**Comment by laverdet** [comment]
node v7 is obsolete and no longer supported by the nodejs team or myself. As a general rule of thumb if you aren't planning on updating nodejs every few weeks you should stick to even-numbered versions because support is quickly dropped for odd-numbered versions. If you do need support for v7 you can build the module on your computer by following the installation instructions [node-gyp](https://github.com/nodejs/node-gyp) on node-gyp and reinstalling fibers.
