### ISSUE TITLE
Error rebuilding on Mac OS X 10.13.2 | Node 8.9.4

### ISSUE THREAD

**Issue by rzec-r7** [laverdet/node-fibers#359]
So I am trying to upgrade to node 8.9.4 but when I try to rebuild fibers is give me an error:

```
> fibers@1.0.15 install /go/src/github.com/my/project/web/app/node_modules/fibers
> node build.js || nodejs build.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import
gyp ERR! stack          ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/rzec/.nvm/versions/node/v8.9.4/bin/node" "/Users/rzec/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /go/src/github.com/my/project/web/app/node_modules/fibers
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The same exact code rebuilds fine on Node 6.11.4.

I have also already done `xcode-select --install`

**Comment by laverdet** [comment]
Current version of fibers is 2.0.0.

1.0.15 is from 2016.

**Comment by laverdet** [comment]
(Please uninstall and reinstall from scratch)
