### ISSUE TITLE
[WINDOWS] Uncaught Error: A dynamic-link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by AlexVFornazieri** [laverdet/node-fibers#362]
My env:
OS: Windows 10 x64
Node: v8.9.4

When trying to run an electron application is returned error below:

ELECTRON_ASAR.js:173 Uncaught Error: A dynamic-link library (DLL) initialization routine failed. (Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.)
\\?\C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\bin\win32-x64-57\fibers.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\fibers.js:24:38)
    at Object.<anonymous> (C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\fibers.js:27:3)

I have already tried to remove the folder node_modules and install again, but without success, the same application in Ubuntu 16.04 LTS runs perfectly without any errors.

**Comment by AlexVFornazieri** [comment]
Problem encountered, there was an import of a module called 'sync' (node-sync) that was not actually being used.

Import removed, with no more errors. Going to close.
