### ISSUE TITLE
2.0.1 fails (when using with fibrous)

### ISSUE THREAD

**Issue by pmeisen** [laverdet/node-fibers#366]
Since the update, I receive errors on any call, I rolled back to `2.0.0` and everything worked fine again.

```
TypeError: Cannot read property 'undefined' of undefined
    at getAndClearStack (/node_modules/fibers/fibers.js:57:38)
    at Fiber.run (/node_modules/fibers/fibers.js:75:17)
    at /node_modules/fibrous/lib/fibrous.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by laverdet** [comment]
What is your nodejs version?

**Comment by pmeisen** [comment]
I'm using `v8.6.0`

**Comment by laverdet** [comment]
Thanks, you should have better luck with 2.0.2 on that version of nodejs.
