### ISSUE TITLE
node 8 error

### ISSUE THREAD

**Issue by zhaoxuan** [laverdet/node-fibers#370]
```
[root@bid1 testdir]# npm i fibers

> fibers@2.0.2 install /data/testdir/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/data/testdir/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/8.11.1/include/node/v8.h:21,
                 from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:334: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:351: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:366: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:395: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/8.11.1/include/node/v8.h:397: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:402: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:442: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/8.11.1/include/node/v8.h:776: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:801: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:813: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:839: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h:1188: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h:1194: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/8.11.1/include/node/v8.h:1743: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:3213: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:3854: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:4123: error: function definition does not declare parameters
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../src/fibers.cc:8:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/data/testdir/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-573.22.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /data/testdir/node_modules/fibers
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/data/testdir/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/8.11.1/include/node/v8.h:21,
                 from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:334: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:351: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:366: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:395: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/8.11.1/include/node/v8.h:397: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:402: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:442: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/8.11.1/include/node/v8.h:776: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:801: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:813: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:839: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h:1188: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h:1194: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/8.11.1/include/node/v8.h:1743: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:3213: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:3854: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:4123: error: function definition does not declare parameters
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../src/fibers.cc:8:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/data/testdir/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-573.22.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /data/testdir/node_modules/fibers
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
npm WARN enoent ENOENT: no such file or directory, open '/data/testdir/package.json'
npm WARN testdir No description
npm WARN testdir No repository field.
npm WARN testdir No README data
npm WARN testdir No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-16T09_19_19_026Z-debug.log
```

**Comment by sjmcdowall** [comment]
This looks a lot like issue 369.. did you read that?

**Comment by laverdet** [comment]
Yeah this is identical to #369. No telling what is causing your issues but it aint my fault! I'll make sure this works for you guys when node v10.x and until then please see my workaround on the other issue.
