### ISSUE TITLE
node-fibers on ARM7

### ISSUE THREAD

**Issue by barbizio** [laverdet/node-fibers#387]
I'm encountering difficulties running node-fibers on an ARM7 system (synology NAS d213j).
I need it to run a builded app from Meteor. To exclude any problem with my Meteor app I downloaded from source and installed on a separate folder then runned the test.js.

I have node 8.11.2, npm 5.6.0, node-gyp v3.8.0 and gcc v6.3.0.

Note that the libstdc++.so.6 error is due of the manual installation of node 8.11.2 over nvm. I think is highly unlikely that is the source of the node-fibers problem, given that with the previous version of node (8.9.4) I had no lib error but the same problem.

the problem I'm facing is the following:

```
/volume1/homes/user/.nvm/versions/node/v8.11.2/bin/node: /lib/libstdc++.so.6: no version information available (required by /volume1/homes/user/.nvm/versions/node/v8.11.2/bin/node)
**(this error multiple times, see description above).......**
## There is an issue with `node-fibers` ##
`/volume1/homes/user/node-fibers/bin/linux-arm-57/fibers.node` is missing.

Try running this to fix the issue: /volume1/homes/user/.nvm/versions/node/v8.11.2/bin/node /volume1/homes/user/node-fibers/build
Error: /volume1/homes/user/node-fibers/bin/linux-arm-57/fibers.node: internal error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/homes/user/node-fibers/fibers.js:13:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
/volume1/homes/user/node-fibers/fibers.js:22
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/volume1/homes/user/node-fibers/fibers.js:22:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/homes/user/node-fibers/test/illegal-yield.js:2:13)
    at Module._compile (module.js:652:30)
```

running the metioned cmd (node build) I have this:

```
`linux-arm-57` exists; testing
Problem with the binary; manual build incoming
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.2 | linux | arm
gyp info spawn /bin/python2
gyp info spawn args [ '/volume1/homes/user/.nvm/versions/node/v8.11.2/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/volume1/homes/user/node-fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/volume1/homes/user/.nvm/versions/node/v8.11.2/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/services/homes/user/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/services/homes/user/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/volume1/homes/user/.nvm/versions/node/v8.11.2/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/services/homes/user/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/volume1/homes/user/node-fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/volume1/homes/user/node-fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/volume1/homes/user/node-fibers/build'
gyp info ok
Installed in `/volume1/homes/user/node-fibers/bin/linux-arm-57/fibers.node`
```
If I then run test.js I'll have the same error all over again.

**Comment by laverdet** [comment]
What happens if you do: `require('/volume1/homes/user/node-fibers/bin/linux-arm-57/fibers.node');` in a nodejs console?

What is the output of: `file /volume1/homes/user/node-fibers/bin/linux-arm-57/fibers.node`

**Comment by laverdet** [comment]
Weird error. Does it happen with other native modules? What about:
```
npm install ref
node -e 'console.log(require("./node_modules/ref/build/Release/binding.node"))'
```
