### ISSUE TITLE
Error installing 3.1.0 on linux

### ISSUE THREAD

**Issue by Kignuf** [laverdet/node-fibers#398]
Hello,

Since yesterday I am having trouble installing fibers 3.1.0 on linux.
node: v8.9.3
linux: debian:stretch-slim

This is running on Jenkins, and the linux is a docker container.

Previous builds were installing fibers 3.0.0 successfully.

Here is the error:
```
> fibers@3.1.0 install /usr/local/lib/node_modules/happn-integration-tests/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57-glibc` exists; testing
Problem with the binary; manual build incoming
[91mgyp[0m[91m WARN EACCES[0m[91m user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.9.3"
[0m[91mgyp WARN[0m[91m EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/happn-integration-tests/node_modules/fibers/.node-gyp"
[0m[91mgyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/happn-integration-tests/node_modules/fibers/.node-gyp/8.9.3"
gyp WARN[0m[91m EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/happn-integration-tests/node_modules/fibers/.node-gyp"
[0m[91mgyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/happn-integration-tests/node_modules/fibers/.node-gyp/8.9.3"
```
It repeats those last lines indefinitly.

Let me  know if you need more information.

Thanks for reading me :)

**Comment by nikodamn** [comment]
```Directory: /var/lib/jenkins/workspace/feeds-and-posts-pr-checks/app/node_modules/fibers
Output:
`linux-x64-64-glibc` exists; testing
Problem with the binary; manual build incoming
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/var/lib/jenkins/workspace/feeds-and-posts-pr-checks/node_env/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
node-gyp exited with code: 1```

**Comment by nikodamn** [comment]
Node: 10.10.0

```error /var/lib/jenkins/workspace/feeds-and-posts-pr-checks/app/node_modules/fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments: 
Directory: /var/lib/jenkins/workspace/feeds-and-posts-pr-checks/app/node_modules/fibers
Output:
`linux-x64-64-glibc` exists; testing
Problem with the binary; manual build incoming
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/var/lib/jenkins/workspace/feeds-and-posts-pr-checks/node_env/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
node-gyp exited with code: 1

**Comment by laverdet** [comment]
Interesting. I've tracked this down to nodejs/node#21269, looks like they unintentionally broke the ABI in nodejs v8.12.0. I'll recompile this for you and get 3.1.1 out later today.

**Comment by laverdet** [comment]
Alright 3.1.1 is on npm, I think that will fix this issue for you. Please reopen if it doesn't.
