### ISSUE TITLE
Can't build fibers on Manjaro Linux

### ISSUE THREAD

**Issue by marinakuranda** [laverdet/node-fibers#403]
Hello! 

I'm tying to install [wdio](https://www.npmjs.com/package/wdio), but it seems like there is a problem.

```
Operating System: Manjaro Linux
Kernel: Linux 4.19.13-1-MANJARO

node -v 
v11.6.0
npm -v
6.5.0
```

Error log without the stack trace from the compiler:

```sh
make: *** [fibers.target.mk:110: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/name/project/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/name/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.19.13-1-MANJARO
gyp ERR! command "/home/name/.nvm/versions/node/v11.6.0/bin/node" "/home/name/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/name/project/node_modules/fibers
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN chai-webdriverio@0.4.3 requires a peer of chai@~4.0.1 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/name/.npm/_logs/2019-01-09T20_57_31_712Z-debug.log

```

Can you help me fixing this?

**Comment by laverdet** [comment]
Current version of fibers is 3.1.1 not 2.0.2.

**Comment by marinakuranda** [comment]
Thanks for pointing that out!
