### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by Fabbok1x** [laverdet/node-fibers#435]
Whatever I do:
fibers.target.mk:120: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/var/www/app/bundle/programs/server/npm/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-88-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /var/www/app/bundle/programs/server/npm/node_modules/fibers
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-13T18_33_59_729Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-13T18_33_59_758Z-debug.log

Happens on:
Ubuntu	18.04
Node Version: v12.16.1

I tried everything. 
 - Removing node_modules, node-gyp. 
 - Removing npm, node.
 - Installing node via NVM
 - Switching versions down to 12.16.0 (it works on another device)

**It will not compile under any circumstances.**

I have checked **every** ticket. There is not a working solution to this problem yet.

**Comment by tcf909** [comment]
It looks like your compiling Fibers version 3.x against node.js 12.x which will not work.

You need to be using the latest Fibers version.

**Comment by tcf909** [comment]
https://github.com/laverdet/node-fibers#supported-platforms
